general.import = ["~/.config/alacritty/themes/themes/nord.toml"]
# change "username" to your computer username
general.working_directory = "/Users/username/Documents"

[env]
  TERM = "xterm-256color"
  COLORTERM = "truecolor"

[window]
  padding = { x = 0, y = 0 }
  decorations = "Buttonless"
  dimensions = { columns = 180, lines = 40 }
  position = { x = 300, y = 185}
  opacity = 0.7
  blur = true
  option_as_alt = "Both"


[font]
  normal.family = "MesloLGL Nerd Font Mono"
  bold.family = "MesloLGL Nerd Font Mono"
  italic.family = "MesloLGL Nerd Font Mono" 
  bold_italic.family = "MesloLGL Nerd Font Mono"
  size = 13

# [colors.primary]
  # foreground = "#a97af5"
  #background = "#252629"

[terminal.shell]
  program = "/opt/homebrew/bin/tmux"




