general.import = ["~/.config/alacritty/themes/themes/tokyo_night_storm.toml"]
general.working_directory = "/Users/xyz.isx/Documents"

[window]
  padding = { x = 5, y = 5 }
  decorations = "Buttonless"
  opacity = 0.8
  blur = true
  option_as_alt = "Both"


[font]
  normal.family = "MesloLGL Nerd Font Mono"
  bold.family = "MesloLGL Nerd Font Mono"
  italic.family = "MesloLGL Nerd Font Mono" 
  bold_italic.family = "MesloLGL Nerd Font Mono"
  size = 12.8

# [colors.primary]
  # foreground = "#a97af5"
  #background = "#252629"

[terminal.shell]
  program = "/opt/homebrew/bin/tmux"

[env]
  TERM = "xterm-256color"
  COLORTERM = "truecolor"


