[window]
  startup_mode = "Fullscreen"

[font]
  normal.family = "MesloLGL Nerd Font Mono"
  bold.family = "MesloLGL Nerd Font Mono"
  italic.family = "MesloLGL Nerd Font Mono" 
  bold_italic.family = "MesloLGL Nerd Font Mono"
  size = 15

[colors.primary]
  foreground = "#a97af5"
  background = "#252629"

[terminal.shell]
  program = "/opt/homebrew/bin/tmux"

[env]
  TERM = "xterm-256color"
  COLORTERM = "truecolor"

